services:
  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    profiles:
     - backend
     - full
    ports:
     - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1

  frontend:
    build: ./frontend/
    container_name: frontend_app
    restart: always
    profiles:
      - frontend
      - full
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/
