services:
  backend:
    build: ./backend
    container_name: backend_prod
    profiles:
     - prod
     - backend
    restart: always
    ports:
     - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1

  frontend_prod:
    build: ./frontend/
    container_name: frontend_prod
    depends_on:
      - backend
    profiles:
      - prod
    restart: always
    ports:
      - "3000:3000"

  frontend_only:
    build: ./frontend/
    container_name: frontend_only_app
    profiles:
      - frontend
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
