name: Deploy Ubuntu Server Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Using appleboy/ssh-action combines key injection and execution
      - name: Deploy with Appleboy SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            #!/bin/bash
            set -e # exit as soon as error raised
            # Use the APP_DIR secret value directly within the script
            APP_DIR="${{ secrets.APP_DIR }}"

            echo 'Deploying application...'


            cd $APP_DIR || exit 1
            pwd
            ls
            git remote set-url origin git@github-deploy:rorypearson26/octopus-visual.git
            git pull origin master

            # Use Docker Compose for zero-downtime update
            docker compose build backend frontend_prod --no-cache --pull
            docker compose --profile full up -d --remove-orphans

            echo 'Deployment complete.'
